# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExAuthor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('refer', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExGallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('root_path', models.CharField(max_length=100)),
                ('save_path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('name_n', models.CharField(max_length=255)),
                ('name_j', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('language', models.IntegerField()),
                ('translator', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('length', models.IntegerField()),
                ('posted', models.DateTimeField()),
                ('is_anthology', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('status', models.IntegerField()),
                ('last_view', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryAuthorRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('author_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryGroupRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('group_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryTagRelation0',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('tag_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryTagRelation1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('tag_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryTagRelation2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('tag_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGalleryTagRelation3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_id', models.IntegerField(db_index=True)),
                ('tag_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('type', models.IntegerField(db_index=True)),
            ],
        ),
    ]
